// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vggfvzaxyonjvyahydup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZ2Z2emF4eW9uanZ5YWh5ZHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTY3NzgsImV4cCI6MjA3MTk5Mjc3OH0.EjGOopDjxUsJpvpUYTAsRA0MJ92kbhRrCtmo9dZuET4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});